In [ ]:
import pickle
import matplotlib.pyplot as plt
import numpy as np

from datasets.gait_fc_dataset import GaitFCDatasetV2

In [ ]:
with open('gait_fc_dataset/train/0/000.pkl', 'rb') as handle:
    negative_vid = pickle.load(handle)

ae_feat = negative_vid['ae_feat']
gei = negative_vid['gei']
print(gei)
plt.imshow(gei)
plt.show()

In [ ]:
gait_fc_dataset = GaitFCDatasetV2('gait_fc_dataset/train')

In [ ]:
a_v, a_gei, target = gait_fc_dataset.__getitem__(0)
print(a_v)

# Mean and Std Calc

In [ ]:
feats = []
for i in range(len(gait_fc_dataset)):
    a_v, a_gei, target = gait_fc_dataset.__getitem__(i)
    for f in a_v:
        print(f)
        feats.append(f)


In [ ]:
feats = np.array(feats)
print(feats.shape)

In [ ]:
means = np.mean(feats, axis=0)
std = np.std(feats, axis=0)
print(means.shape)
print(std.shape)
print(means)

In [ ]:
print(feats.shape)

In [ ]:
with open('gait_fc_dataset/train/13/001.pkl', 'rb') as handle:
    negative_vid = pickle.load(handle)

ae_feat = negative_vid['ae_feat']
gei = negative_vid['gei']
# print(ae_feat)

# ae_feat = (ae_feat[25] - means)/std
# print(ae_feat)

In [ ]:
np.save('src/means_ae.npy', means)
np.save('src/std_ae.npy', std)

In [18]:
m = np.array([np.load('src/means_ae.npy')] * 40)
s = np.array([np.load('src/std_ae.npy')]*40)
print(m)
print(s.shape)

[[ 9.55755826  9.55727318  9.54807538 ...  9.58110074 10.59562032
  10.59229939]
 [ 9.55755826  9.55727318  9.54807538 ...  9.58110074 10.59562032
  10.59229939]
 [ 9.55755826  9.55727318  9.54807538 ...  9.58110074 10.59562032
  10.59229939]
 ...
 [ 9.55755826  9.55727318  9.54807538 ...  9.58110074 10.59562032
  10.59229939]
 [ 9.55755826  9.55727318  9.54807538 ...  9.58110074 10.59562032
  10.59229939]
 [ 9.55755826  9.55727318  9.54807538 ...  9.58110074 10.59562032
  10.59229939]]
(40, 324)


In [20]:
feat = (ae_feat - m)/s
print(ae_feat)
print(feat)
print(feat.max(), feat.min())

[[ 9.56068993  9.56068993  9.56068993 ... 10.585186   10.60636711
  10.60636711]
 [ 9.56068993  9.56068993  9.56068993 ... 10.60636711 10.60636711
  10.60636711]
 [ 9.56068993  9.56068993  9.56068993 ... 10.60636711 10.60636711
  10.60636711]
 ...
 [ 9.56068993  9.56068993  9.56068993 ... 10.60636711 10.60636711
  10.60636711]
 [ 9.56068993  9.56068993  9.56068993 ... 10.60636711 10.60636711
  10.60636711]
 [ 9.56068993  9.56068993  9.56068993 ... 10.60636711 10.60636711
  10.60636711]]
[[0.02655404 0.02548742 0.04795689 ... 0.43949341 0.03926129 0.07056594]
 [0.02655404 0.02548742 0.04795689 ... 0.44876449 0.03926129 0.07056594]
 [0.02655404 0.02548742 0.04795689 ... 0.44876449 0.03926129 0.07056594]
 ...
 [0.02655404 0.02548742 0.04795689 ... 0.44876449 0.03926129 0.07056594]
 [0.02655404 0.02548742 0.04795689 ... 0.44876449 0.03926129 0.07056594]
 [0.02655404 0.02548742 0.04795689 ... 0.44876449 0.03926129 0.07056594]]
5.344346121903834 -7.189089504972724


In [21]:
print(len(set(gait_fc_dataset.target)))

400
